EXECUTE BLOCK AS BEGIN
	INSERT INTO PRODUTO (DESCRICAO,PRECO_VENDA) VALUES ('Smartphone Android X',1599.90);
	INSERT INTO PRODUTO (DESCRICAO,PRECO_VENDA) VALUES ('Notebook i7 16GB',4500.00);
	INSERT INTO PRODUTO (DESCRICAO,PRECO_VENDA) VALUES ('Monitor 24 Polegadas',850.50);
	INSERT INTO PRODUTO (DESCRICAO,PRECO_VENDA) VALUES ('Teclado Mecânico RGB',299.00);
	INSERT INTO PRODUTO (DESCRICAO,PRECO_VENDA) VALUES ('Mouse Gamer Wireless',150.00);
	INSERT INTO PRODUTO (DESCRICAO,PRECO_VENDA) VALUES ('Headset Noise Cancelling',420.00);
	INSERT INTO PRODUTO (DESCRICAO,PRECO_VENDA) VALUES ('Impressora Jato de Tinta',680.00);
	INSERT INTO PRODUTO (DESCRICAO,PRECO_VENDA) VALUES ('Roteador Wi-Fi 6',350.75);
	INSERT INTO PRODUTO (DESCRICAO,PRECO_VENDA) VALUES ('HD Externo 1TB',310.00);
	INSERT INTO PRODUTO (DESCRICAO,PRECO_VENDA) VALUES ('Webcam Full HD',220.00);
	INSERT INTO PRODUTO (DESCRICAO,PRECO_VENDA) VALUES ('Cadeira Ergonômica',1200.00);
	INSERT INTO PRODUTO (DESCRICAO,PRECO_VENDA) VALUES ('Suporte para Monitor',89.90);
	INSERT INTO PRODUTO (DESCRICAO,PRECO_VENDA) VALUES ('Cabo HDMI 2.1',45.00);
	INSERT INTO PRODUTO (DESCRICAO,PRECO_VENDA) VALUES ('Carregador Portátil 20000mAh',180.00);
	INSERT INTO PRODUTO (DESCRICAO,PRECO_VENDA) VALUES ('Mesa de Escritório',450.00);
END;